"""
file: train_deeplabv3plus_all_config.py

brief:  this script trains a DeepLabV3+ blood segmentation model on all
        the selected grouped configurations generated by
        create_grouped_split.py.

    Every Rabbani configuration contains a separate train.csv and validation.csv.
    The test.csv file is not loaded by this script and does not influence
    model training or checkpoint selection.

    For each configuration, a new DeepLabV3+ model is created from
    scratch using a ResNet-18 encoder pretrained on ImageNet. Both the
    pretrained encoder and the segmentation decoder parameters are updated
    during training.

    DeepLabV3+ uses atrous convolutions and an Atrous Spatial Pyramid Pooling
    module to capture image context at multiple receptive-field scales.
    Its decoder also combines high-level features with low-level encoder
    features to recover sharper object boundaries.

    Training images use the augmentation pipeline returned by
    create_train_transform, while validation images use create_eval_transform.

    The script supports binary and multiclass segmentation:

    - Binary segmentation:
      the model produces one output channel. The loss is the sum of
      BCEWithLogitsLoss and DiceLoss.

    - Multiclass segmentation:
      the model produces one channel for every class and uses
      CrossEntropyLoss.

    At the end of every epoch, the script computes validation loss, global
    blood IoU, global blood Dice, mean per-image IoU and mean per-image Dice.

    The best checkpoint for each configuration is selected using the lowest
    validation loss. The checkpoint stores the model parameters, the best
    epoch, the best validation loss and the validation metrics associated with
    that epoch.

    Positional arguments:

        first argument:  number of epochs
        second argument: number of configurations to train

    When no arguments are provided, the script trains for 50 epochs and uses
    every available config_XXX directory.

"""

import gc
import os
import random
import sys
from pathlib import Path
import numpy as np
import segmentation_models_pytorch as smp
import torch
from src.data_transforms import create_bleed_train_transform, create_bleed_eval_transform
from src.hemoset_dataset_v2 import CustomImageDataset
from src import config_split
from torch.utils.data import DataLoader


# COMMANDS USED ONLY TO RUN THE TRAINING FROM THE BASH SCRIPT
# The installed cuDNN version does not support the Tesla K80 GPU.
torch.backends.cudnn.enabled = False

# Disable NNPACK to avoid unsupported hardware warnings on the CPU node.
torch.backends.nnpack.set_flags(False)


# ============================================================
# GENERAL SETTINGS
# ============================================================

device = "cuda"

batch_size = 4
num_workers = 2

encoder_name = "resnet18"
learning_rate = 0.001

random_seed = 42

# The script is located in:
# lab/k_fold/rabbani/training/train_deeplabv3plus_all_config.py
lab_directory = Path(__file__).resolve().parents[3]

splits_directory = (
    lab_directory
    / "k_fold"
    / "rabbani"
    / "generated_splits"
)

checkpoint_directory = (
    Path("/work/cvcs2026/latent_space_cowboys/model_pretrained")
    / "k_fold"
    / "rabbani"
    / "deeplabv3plus_resnet18"
    / config_split.SEGMENTATION_MODE
)


# ============================================================
# INPUT ARGUMENTS
# ============================================================

# First argument: number of epochs.
if len(sys.argv) > 1 and sys.argv[1] != "":
    n_epochs = int(sys.argv[1])
else:
    n_epochs = 50

# Second argument: number of configurations.
# None means all available configurations.
if len(sys.argv) > 2 and sys.argv[2] != "":
    n_configurations = int(sys.argv[2])
else:
    n_configurations = None

if len(sys.argv) > 3:
    raise ValueError(
        "Usage: python -m k_fold.rabbani.training.train_deeplabv3plus_all_config "
        "[epochs] [number_of_configurations]"
    )

if n_epochs <= 0:
    raise ValueError("The number of epochs must be greater than zero.")

if n_configurations is not None and n_configurations <= 0:
    raise ValueError("The number of configurations must be greater than zero.")


# ============================================================
# SEGMENTATION SETTINGS
# ============================================================

segmentation_mode = config_split.SEGMENTATION_MODE.strip().lower()

if segmentation_mode == "binary":
    output_classes = 1
else:
    output_classes = config_split.NUM_CLASSES


"""
function: set_random_seed
brief:    this routine sets all random seeds before training one configuration
"""
def set_random_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


"""
function: prepare_mask
brief:    this routine prepares the mask for the selected loss
"""
def prepare_mask(mask, mode):
    if mode == "binary":
        return (mask > 0).float().to(device)
    else:
        return torch.squeeze(mask, 1).to(torch.long).to(device)


"""
function: compute_loss
brief:    this routine computes the selected loss depending on segmentation mode
"""
def compute_loss(mode, logits, mask, bce_loss, dice_loss, ce_loss):
    if mode == "binary":
        bce_value = bce_loss(logits, mask)
        dice_value = dice_loss(logits, mask)
        return bce_value + dice_value
    else:
        return ce_loss(logits, mask)


"""
function: get_predictions
brief:    this routine converts model logits into the final predicted mask
"""
def get_predictions(logits, mode):
    if mode == "binary":
        return (torch.sigmoid(logits) >= config_split.BINARY_THRESHOLD).long()
    else:
        return logits.argmax(dim=1)


"""
function: get_segmentation_stats
brief:    this routine retrieves TP, FP, FN and TN for every image
"""
def get_segmentation_stats(predictions, mask, mode):
    if mode == "binary":
        return smp.metrics.get_stats(predictions, mask.long(), mode=mode)
    else:
        return smp.metrics.get_stats(
            predictions,
            mask,
            mode=mode,
            num_classes=config_split.NUM_CLASSES,
        )


"""
function: get_class_target
brief:    this routine retrieves metric values for the blood class
"""
def get_class_target(target_class, mode):
    if mode == "binary":
        return target_class[0]
    else:
        return target_class[1]


"""
function: get_image_class_target
brief:    this routine retrieves per-image metric values for the blood class
"""
def get_image_class_target(target_class, mode):
    if mode == "binary":
        return target_class[:, 0]
    else:
        return target_class[:, 1]


"""
function: compute_metrics
brief:    this routine computes global and per-image IoU and Dice
"""
def compute_metrics(tp, fp, fn, tn, mode):
    image_iou_classes = smp.metrics.iou_score(tp, fp, fn, tn, reduction="none")
    image_dice_classes = smp.metrics.f1_score(tp, fp, fn, tn, reduction="none")

    image_iou = get_image_class_target(image_iou_classes, mode)
    image_dice = get_image_class_target(image_dice_classes, mode)

    global_tp = tp.sum(dim=0)
    global_fp = fp.sum(dim=0)
    global_fn = fn.sum(dim=0)
    global_tn = tn.sum(dim=0)

    global_iou_classes = smp.metrics.iou_score(
        global_tp,
        global_fp,
        global_fn,
        global_tn,
        reduction="none",
    )

    global_dice_classes = smp.metrics.f1_score(
        global_tp,
        global_fp,
        global_fn,
        global_tn,
        reduction="none",
    )

    global_iou = get_class_target(global_iou_classes, mode)
    global_dice = get_class_target(global_dice_classes, mode)

    return {
        "global_iou": global_iou.item(),
        "global_dice": global_dice.item(),
        "image_iou_mean": image_iou.mean().item(),
        "image_iou_std": image_iou.std(unbiased=False).item(),
        "image_dice_mean": image_dice.mean().item(),
        "image_dice_std": image_dice.std(unbiased=False).item(),
    }


"""
function: get_configuration_number
brief:    this routine extracts the numeric identifier from config_XXX
"""
def get_configuration_number(configuration_directory):
    return int(configuration_directory.name.split("_")[-1])


"""
function: get_configuration_directories
brief:    this routine retrieves and sorts the configuration directories
"""
def get_configuration_directories():
    if not splits_directory.is_dir():
        raise FileNotFoundError(f"Split directory not found: {splits_directory}")

    configuration_directories = [
        path
        for path in splits_directory.glob("config_*")
        if path.is_dir()
    ]

    configuration_directories.sort(key=get_configuration_number)

    if not configuration_directories:
        raise RuntimeError("No config_XXX directories were found.")

    if n_configurations is not None:
        if n_configurations > len(configuration_directories):
            raise ValueError(
                f"Requested {n_configurations} configurations, "
                f"but only {len(configuration_directories)} are available."
            )

        configuration_directories = configuration_directories[:n_configurations]

    return configuration_directories


"""
function: create_data_loaders
brief:    this routine creates train and validation DataLoaders for one config
"""
def create_data_loaders(configuration_directory):
    train_csv_path = configuration_directory / "train.csv"
    valid_csv_path = configuration_directory / "validation.csv"

    if not train_csv_path.is_file():
        raise FileNotFoundError(f"Train CSV not found: {train_csv_path}")

    if not valid_csv_path.is_file():
        raise FileNotFoundError(f"Validation CSV not found: {valid_csv_path}")

    train_transform = create_bleed_train_transform()
    eval_transform = create_bleed_eval_transform()

    train_ds = CustomImageDataset(str(train_csv_path), train_transform)
    valid_ds = CustomImageDataset(str(valid_csv_path), eval_transform)

    train_rabbani_DL = DataLoader(
        train_ds,
        batch_size,
        num_workers=num_workers,
        shuffle=True,
        drop_last=True,
    )

    valid_rabbani_DL = DataLoader(
        valid_ds,
        batch_size,
        num_workers=num_workers,
        shuffle=False,
    )

    return train_rabbani_DL, valid_rabbani_DL


"""
function: create_model
brief:    this routine creates a new DeepLabV3+ ResNet-18 model
"""
def create_model():
    deeplabv3plus = smp.DeepLabV3Plus(
        encoder_name=encoder_name,
        encoder_weights="imagenet",
        in_channels=3,
        classes=output_classes,
    )

    return deeplabv3plus.to(device)


"""
function: save_checkpoint
brief:    this routine safely saves the best checkpoint for one config
"""
def save_checkpoint(checkpoint, checkpoint_path):
    checkpoint_path.parent.mkdir(parents=True, exist_ok=True)

    temporary_path = checkpoint_path.with_suffix(
        checkpoint_path.suffix + ".tmp"
    )

    torch.save(checkpoint, temporary_path)
    os.replace(temporary_path, checkpoint_path)


# ============================================================
# TRAINING ALL CONFIGURATIONS
# ============================================================

if not torch.cuda.is_available():
    raise RuntimeError("CUDA is not available.")

os.makedirs(checkpoint_directory, exist_ok=True)

configuration_directories = get_configuration_directories()

print(f"number of epochs: {n_epochs}")
print(f"number of configurations: {len(configuration_directories)}")
print(f"segmentation mode: {segmentation_mode}")

all_training_results = []

for configuration_directory in configuration_directories:
    configuration_id = get_configuration_number(configuration_directory)

    print("")
    print("============================================================")
    print(f"CONFIGURATION: {configuration_id:03d}")
    print("============================================================")

    set_random_seed(random_seed)

    train_rabbani_DL, valid_rabbani_DL = create_data_loaders(configuration_directory)

    print(f"train images: {len(train_rabbani_DL.dataset)}")
    print(f"validation images: {len(valid_rabbani_DL.dataset)}")

    train_img, train_mask = next(iter(train_rabbani_DL))
    print(f"Feature batch shape: {train_img.size()}")
    print(f"Labels batch shape: {train_mask.size()}")

    deeplabv3plus = create_model()
    print(encoder_name)

    adam = torch.optim.Adam(deeplabv3plus.parameters(), lr=learning_rate)

    scheduler = torch.optim.lr_scheduler.MultiStepLR(
        adam,
        milestones=[10],
        gamma=0.1,
    )

    bce_loss = torch.nn.BCEWithLogitsLoss().to(device)

    dice_loss = smp.losses.DiceLoss(
        mode=segmentation_mode,
        from_logits=True,
    ).to(device)

    ce_loss = torch.nn.CrossEntropyLoss().to(device)

    checkpoint_path = (
        checkpoint_directory
        / f"deeplabv3plus_rab_{segmentation_mode}_best_{encoder_name}_config_{configuration_id:03d}.pth"
    )

    best_val_loss = float("inf")
    best_epoch = 0
    best_metrics = None

    for epoch in range(n_epochs):
        print(f"------------ EPOCH: {epoch + 1} ------------")

        # TRAINING
        deeplabv3plus.train()

        train_loss_sum = 0

        for i, (train_img, train_mask) in enumerate(train_rabbani_DL):
            # Reset gradients before the new update.
            adam.zero_grad()

            train_mask = prepare_mask(train_mask, segmentation_mode)
            train_img = train_img.to(device)

            # Forward pass and training loss.
            img_forward = deeplabv3plus(train_img)

            loss_train_value = compute_loss(
                segmentation_mode,
                img_forward,
                train_mask,
                bce_loss,
                dice_loss,
                ce_loss,
            )

            if i % 50 == 0:
                print(f"loss_train {loss_train_value}")

            train_loss_sum += loss_train_value.item()

            # Backpropagation and parameter update.
            loss_train_value.backward()
            adam.step()

        train_batch_num = len(train_rabbani_DL)
        avg_train_loss = train_loss_sum / train_batch_num

        # VALIDATION
        deeplabv3plus.eval()

        val_loss_sum = 0

        tp_list = []
        fp_list = []
        fn_list = []
        tn_list = []

        # Validation does not update model parameters.
        with torch.no_grad():
            for j, (val_img, val_mask) in enumerate(valid_rabbani_DL):
                val_mask = prepare_mask(val_mask, segmentation_mode)
                val_img = val_img.to(device)

                # Forward pass on the validation batch.
                img_forward = deeplabv3plus(val_img)

                loss_valid_value = compute_loss(
                    segmentation_mode,
                    img_forward,
                    val_mask,
                    bce_loss,
                    dice_loss,
                    ce_loss,
                )

                if j % 50 == 0:
                    print(f"loss_valid {loss_valid_value}")

                val_loss_sum += loss_valid_value.item()

                # Convert logits into masks and collect confusion statistics.
                final_map = get_predictions(img_forward, segmentation_mode)

                batch_tp, batch_fp, batch_fn, batch_tn = get_segmentation_stats(
                    final_map,
                    val_mask,
                    segmentation_mode,
                )

                tp_list.append(batch_tp.cpu())
                fp_list.append(batch_fp.cpu())
                fn_list.append(batch_fn.cpu())
                tn_list.append(batch_tn.cpu())

        val_batch_num = len(valid_rabbani_DL)
        avg_val_loss = val_loss_sum / val_batch_num

        # Compute global and per-image validation metrics.
        validation_metrics = compute_metrics(
            torch.cat(tp_list, dim=0),
            torch.cat(fp_list, dim=0),
            torch.cat(fn_list, dim=0),
            torch.cat(tn_list, dim=0),
            segmentation_mode,
        )

        current_lr = scheduler.get_last_lr()[0]

        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            best_epoch = epoch + 1
            best_metrics = dict(validation_metrics)

            # saves, with the weights, also these info in the checkpoint.pth
            checkpoint = {
                "configuration_id": configuration_id,
                "dataset_name": "rabbani",
                "dataset_tag": "rab",
                "model_name": "deeplabv3plus",
                "encoder_name": encoder_name,
                "segmentation_mode": segmentation_mode,
                "output_classes": output_classes,
                "epoch": best_epoch,
                "best_validation_loss": best_val_loss,
                "validation_metrics": best_metrics,
                "model_state_dict": deeplabv3plus.state_dict(),
                "optimizer_state_dict": adam.state_dict(),
            }

            save_checkpoint(checkpoint, checkpoint_path)

            print(
                f"new best checkpoint: epoch {best_epoch}, "
                f"validation loss {best_val_loss:.6f}"
            )

        scheduler.step()

        print(f"learning_rate {current_lr}")
        print(f"----- Avg values for epoch {epoch + 1} -----")
        print(f"avg_train_loss {avg_train_loss}")
        print(f"avg_val_loss {avg_val_loss}")
        print(f"global_iou {validation_metrics['global_iou']}")
        print(f"global_dice {validation_metrics['global_dice']}")
        print(
            f"image_iou "
            f"{validation_metrics['image_iou_mean']} "
            f"+/- {validation_metrics['image_iou_std']}"
        )
        print(
            f"image_dice "
            f"{validation_metrics['image_dice_mean']} "
            f"+/- {validation_metrics['image_dice_std']}"
        )

    if best_metrics is None:
        raise RuntimeError(
            f"No checkpoint was saved for configuration {configuration_id:03d}."
        )

    all_training_results.append(
        {
            "configuration_id": configuration_id,
            "best_epoch": best_epoch,
            "best_validation_loss": best_val_loss,
            "best_validation_global_iou": best_metrics["global_iou"],
            "best_validation_global_dice": best_metrics["global_dice"],
            "checkpoint_path": str(checkpoint_path),
        }
    )

    print("")
    print("----- BEST VALIDATION CHECKPOINT -----")
    print(f"best_epoch {best_epoch}")
    print(f"best_val_loss {best_val_loss}")
    print(f"best_global_iou {best_metrics['global_iou']}")
    print(f"best_global_dice {best_metrics['global_dice']}")
    print(
        f"best_image_iou "
        f"{best_metrics['image_iou_mean']} "
        f"+/- {best_metrics['image_iou_std']}"
    )
    print(
        f"best_image_dice "
        f"{best_metrics['image_dice_mean']} "
        f"+/- {best_metrics['image_dice_std']}"
    )
    print(f"checkpoint {checkpoint_path}")

    del train_rabbani_DL
    del valid_rabbani_DL
    del deeplabv3plus
    del adam
    del scheduler

    gc.collect()
    torch.cuda.empty_cache()


# ============================================================
# FINAL TRAINING SUMMARY
# ============================================================

print("")
print("============================================================")
print("FINAL TRAINING SUMMARY")
print("============================================================")

for result in all_training_results:
    print(
        f"config {result['configuration_id']:03d} | "
        f"best epoch {result['best_epoch']} | "
        f"validation loss {result['best_validation_loss']:.6f} | "
        f"global Dice {result['best_validation_global_dice']:.4f}"
    )